### ISSUE TITLE
关于课程期末的疑问

### ISSUE THREAD

**Issue by TTTTTTi** [labyrinth-ssr/HDFS-Corba#2]
学长（或者学姐？），请问能问一下分布式期末应该怎么复习吗？看书好抽象55555
还有考试大概考什么您还记得吗？qaq救救孩子

**Comment by labyrinth-ssr** [comment]
我期中退课了QAQ（还好是选修

**Comment by TTTTTTi** [comment]
qaq,我们是必修，这世界到底有没有人曾经修过这门，啊啊啊啊啊

**Comment by marJudge** [comment]
这么厉害，都要期中退课的吗T-T

**Comment by labyrinth-ssr** [comment]
> 这么厉害，都要期中退课的吗T-T

两学分事儿这么多的课，多一事不如少一事
